packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  '@fontsource/ibm-plex-mono': ^5.3.0
  '@hono/zod-validator': ^0.9.1
  '@mdi/font': ^7.4.47
  '@tanstack/vue-query': ^5.103.1
  '@types/google.accounts': ^0.0.18
  '@types/node': ^24
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vite-plus: 1.0.0
  zod: ^4.6.5
overrides:
  vite@*: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
allowBuilds:
  esbuild: true
  vue-demi: true
  workerd: true
minimumReleaseAgeExclude:
  - tsx@4.23.14
